### ISSUE TITLE
[AVM Module Issue]: Set nullable false on collection variables

### ISSUE THREAD

**Issue by adammontlake** [Azure/terraform-azurerm-avm-res-network-expressroutecircuit#34]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

Per TFNFR20 - validate that all collection variables nullable = false.
The following vars should be included:
express_route_circuit_authorizations
peerings
vnet_gw_connections

**Comment by adammontlake** [comment]
@jchancellor-ms 
As per the TFNFR20 we need to set nullable = false, but in our case, all the above mentioned variables can be empty. They all have a default = {} for a purpose - if a circuit is just being created, before provision is complete, a user cannot set peerings or connections. Regarding the authorizations, they might not be required if the connection is in the same tenant.

What are the AVM guidelines in this case?

**Comment by matt-FFFFFF** [comment]
@adammontlake can you give an example?

A default of empty map `{}` is fine and perfectly compatible with `nullable = false`

**Comment by adammontlake** [comment]
Thanks @matt-FFFFFF 
This will be solved as part of pr #29
