### ISSUE TITLE
Allow azurerm versions  >= 3.100, < 4.0

### ISSUE THREAD

**Issue by Philippe3141** [Azure/terraform-azurerm-avm-res-network-expressroutecircuit#43]
Hi,

Could you change the version constraint on azurerm provider declared in terraform.tf to allow versions >= 3.100, < 4.0 ?

Thanks,

Philippe.

**Comment by adammontlake** [comment]
Hey @Philippe3141, thank you very much for submitting this bug!
The reason we are limiting the version to 3.99 is this [bug](https://github.com/hashicorp/terraform-provider-azurerm/issues/26746). An expressroute is not worth very much if you can't create connections for it ;) 

There is a fix for v3.116.0, which is the final release of v3, leaving this bug open to discuss supporting this specific version.
