### ISSUE TITLE
[AVM Question/Feedback]:

### ISSUE THREAD

**Issue by gurretl** [Azure/terraform-azurerm-avm-res-network-expressroutecircuit#48]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Hi,

it seems that the tag v0.2.0 is not applied on the last commit pushed on the main branch where the following fix is available
```
azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.116.0, < 4.0"
    }
```
Can you please fix it if it's a mistake ?

As a workaround, I will configure the source parameter with the github repository : 
```
module "exr_circuit" {
  source = "github.com/Azure/terraform-azurerm-avm-res-network-expressroutecircuit?ref=main"
...
```

Instead of the following: 
```
module "exr_circuit" {
  source                = "Azure/avm-res-network-expressroutecircuit/azurerm"
  version               = "0.2.0"
...
```

Thank you very much!

Lionel

**Comment by adammontlake** [comment]
Hey @gurretl 
Thanks for noticing.
I'm aware of this, it's because there is a small issue with the CICD and I want to make sure all test pass before I create a new release.

I expect it will be solved today, or at the latest very early next week.

**Comment by adammontlake** [comment]
One more note @gurretl 
I would reference the specific commit instead of just main, so that your not surprised by any changes we push, and we plan to push support for AzureRM v4 very soon.

**Comment by adammontlake** [comment]
@gurretl - v0.2.1 is now out
